development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: lr_development
  username: root
  password: mysqlG@llo
  pool: 5
  socket: /var/run/mysqld/mysqld.sock

test: &test
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: lr_production
  username: root
  password: mysqlG@llo
  pool: 5
  socket: /var/run/mysqld/mysqld.sock

cucumber:
  <<: *test
