development:
  chat_server: 'http://localhost:8080'
  shoutcast: &shoutcast
    base:   'http://localhost:3000'
    stream: '/laberinto'
    auth:
      username: 'admin'
      password: 'laberintoadmin'

production:
  chat_server: 'http://184.169.162.15:8080'
  shoutcast:
    base:   'http://laberintoradio.net:8000'
    stream: '/laberinto'
