development:
  chat_server: 'http://localhost:8080'
  shoutcast: 'http://laberintoradio.net:8000/laberinto'

production:
  chat_server: 'http://184.169.162.15:8080'
  shoutcast: 'http://laberintoradio.net:8000/laberinto'
